name: Delete statuses
run-name: ${{ github.actor }} is deleting statuses
on:
  workflow_dispatch:
    inputs:
      since_minutes_ago:
        description: 'Since how many minutes ago'
        required: true
        default: 60

jobs:
  Delete-Statuses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: poetry install
      - name: List working directory
        run:  echo "${{ github.workspace }}"
      - name: Delete statuses
        run: poetry run python3 delete_statuses.py ${{ github.event.inputs.since_minutes_ago }}
        env: # Or as an environment variable
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
