name: Delete statuses from last hour
run-name: ${{ github.actor }} is deleting statuses for the last hour
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: poetry install
      - name: List working directory
        run:  echo "${{ github.workspace }}"
      - name: Delete statuses
        run: poetry run python3 delete_statuses.py
      - run: echo "🍏 This job's status is ${{ job.status }}."
