name: pytest
on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
        # see details (matrix, python-version, python-version-file, etc.)
        # https://github.com/actions/setup-python
      - run: poetry install
      - name: Run the automated tests (for example)
        run: poetry run pytest
