name: ruff
on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: poetry install --with dev
      - name: Check formatting
        run: poetry run ruff format --check .
      - name: Lint
        run: poetry run ruff check .
