name: Update account
run-name: Updating account
on:
  schedule:
    - cron: "0 9 * * *" # At 9AM
#    - cron: "*/30 * * * *" # Every 30 minutes
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Print votes to stdout instead of posting and keep current state'
        required: false
        default: false
      override_unsafe_state_check:
        description: 'Override safety checks when unsafe state is detected (too many new votes or last post ID mismatch)'
        required: false
        default: false
      override_unsafe_state_skip_posts_before_iso_date:
        description: 'minimum ISO date for votes to be posted, votes before that date will be skipped'
        required: false
        default: '9999-12-31'

jobs:
  Update-Account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: poetry install
      - name: Update account
        run: poetry run python3 -m votacoes_assembleia_da_republica.update_account --github-state
        env:
          GH_VARIABLE_UPDATE_TOKEN: ${{ secrets.GH_VARIABLE_UPDATE_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_PATH: ${{ github.repository }}

          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          DEBUG_MODE: ${{ github.event.inputs.debug_mode }}
          OVERRIDE_UNSAFE_STATE_CHECK: ${{ github.event.inputs.override_unsafe_state_check }}
          OVERRIDE_UNSAFE_STATE_SKIP_POSTS_BEFORE_ISO_DATE: ${{ github.event.inputs.override_unsafe_state_skip_posts_before_iso_date }}
      - name: Archive state
        uses: actions/upload-artifact@v4
        with:
          name: publish-vote-state-${{ github.run_id }}
          path: state.json
