name: Update account
run-name: Updating account
on:
  schedule:
    - cron: "0 9 * * *" # At 9AM
#    - cron: "*/30 * * * *" # Every 30 minutes
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Print votes to stdout instead of posting'
        required: false
        default: false
      mark_all_as_published:
        description: 'Mark all existing votes as published'
        required: false
        default: false
      override_too_many_new_votes_check:
        description: 'Override safety check when too many new votes are detected'
        required: false
        default: false

jobs:
  Update-Account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: poetry install
      - name: Fetch existing state
        continue-on-error: true
        uses: actions/cache/restore@v4
        with:
          key: publish-vote-state
          restore-keys: publish-vote-state-
          path: state.json
      - name: Update account
        run: poetry run python3 -m votacoes_assembleia_da_republica.update_account
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          DEBUG_MODE: ${{ github.event.inputs.debug_mode }}
          MARK_ALL_AS_PUBLISHED: ${{ github.event.inputs.mark_all_as_published }}
          OVERRIDE_TOO_MANY_NEW_VOTES_CHECK: ${{ github.event.inputs.override_too_many_new_votes_check }}
      - name: Persist new state
        uses: actions/cache/save@v4
        with:
          key: publish-vote-state-${{ github.run_id }}
          path: state.json
      - name: Archive new state
        uses: actions/upload-artifact@v4.0.0
        with:
          name: publish-vote-state-${{ github.run_id }}
          path: state.json
