name: Update account
run-name: Updating account
on:
  schedule:
    - cron: "0 * * * *" # Every hour
#    - cron: "*/30 * * * *" # Every 30 minutes
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Print votes to stdout instead of posting'
        required: false
        default: false
      skip_all:
        description: 'Mark all existing votes as skipped'
        required: false
        default: false

jobs:
  Update-Account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: poetry install
      - name: Fetch existing state
        continue-on-error: true
        uses: actions/cache/restore@v4
        with:
          key: publish-vote-state
          restore-keys: publish-vote-state-
          path: state.json
      - name: Update account
        run: poetry run python3 update_account.py
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          DEBUG_MODE: ${{ github.event.inputs.debug_mode }}
          SKIP_ALL: ${{ github.event.inputs.skip_all }}
      - name: Persist new state
        uses: actions/cache/save@v4
        with:
          key: publish-vote-state-${{ github.run_id }}
          path: state.json
