name: Update account
run-name: Updating account
on:
  schedule:
    - cron: "0 9 * * *" # At 9AM
#    - cron: "*/30 * * * *" # Every 30 minutes
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Print votes to stdout instead of posting and keep current state'
        required: false
        default: false
      override_too_many_new_votes_check:
        description: 'Override safety check when too many new votes are detected'
        required: false
        default: false
      override_too_many_new_votes_allow_after_iso_date:
        description: 'ISO date after which new votes will be allowed if too many are detected'
        required: false
        default: '9999-12-31'

jobs:
  Update-Account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - run: poetry install
      - name: Download state
        uses: actions/download-artifact@v4
        with:
          name: publish-vote-state-11338422268 # TODO: rename to -latest after fixing current issue with the state
          path: state.json
      - name: Update account
        run: poetry run python3 -m votacoes_assembleia_da_republica.update_account
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          DEBUG_MODE: ${{ github.event.inputs.debug_mode }}
          OVERRIDE_TOO_MANY_NEW_VOTES_CHECK: ${{ github.event.inputs.override_too_many_new_votes_check }}
          OVERRIDE_TOO_MANY_NEW_VOTES_ALLOW_AFTER_ISO_DATE: ${{ github.event.inputs.override_too_many_new_votes_allow_after_iso_date }}
      - name: Persist state
        uses: actions/upload-artifact@v4
        with:
          name: publish-vote-state-latest
          path: state.json
      - name: Archive new state
        uses: actions/upload-artifact@v4
        with:
          name: publish-vote-state-${{ github.run_id }}
          path: state.json
